version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: testing-api_development
      POSTGRES_USER: testing-api
      POSTGRES_PASSWORD: 12345
    ports:
      - '5434:5432'

  database-test:
    image: postgres
    environment:
      POSTGRES_DB: testing-api_test
      POSTGRES_USER: testing-api
      POSTGRES_PASSWORD: 12345
    ports:
      - '5435:5432'